image: node:16-slim


stages:
  - test
  - package
  - publish

variables:
  BUILD_PATH: "/Unittests-tmp"
  WS_ROOT: $CI_PROJECT_DIR

lint:
  stage: test
  script:
    - echo $CI_BUILDS_DIR
    - npm ci
    - npm run lint

test-integration:
  stage: test
  variables:
    DISPLAY: ':99.0'
    MY_VAR: 'l:\Datas'
  script:
    - /bin/mkdir -p $CI_PROJECT_DIR$BUILD_PATH
    - /usr/bin/touch ~/.zsh_history
    - apt-get update
    - apt-get install -y xvfb libxtst6 libnss3 libgtk-3-0 libgbm-dev libxss1 libasound2 libsecret-1-0 git dbus
    - npm ci
    - echo $DISPLAY
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - yarn test-integration

package:
  stage: package
  script:
    - npm ci
    - chown -R root $CI_PROJECT_DIR
    - npm i vsce
    - npx vsce package
  artifacts:
    paths:
      - '*.vsix'
    expire_in: 1 year
  only:
    - tags

publish_marketplace:
  stage: publish
  script:
    - npm install typescript
    - npx vsce publish -p $AZURE_ACCESS_TOKEN
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+\-release/'


publish_open_vsx:
  stage: publish
  script:
    - npx ovsx publish -p $OPENVSX_ACCESS_TOKEN
  when: manual
  only:
    - tags
